{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### My console is red again: Handling  <span style=\"color:red;\">exceptions </span> with python\n",
    "Every novice programmer gets to know exceptions very soon and learns to love them very quickly. But you can use them to your advantage! In the following, we look at:\n",
    "- A way to handle an occurring exceptions.\n",
    "- Raising exceptions ourselves\n",
    "- Creating custom exceptions\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "8482d5ee",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Who hasn't had it before? Getting a ZeroDivisionError when dividing by 0\n",
    "# by accident somewhere during a numerical computation\n",
    "\n",
    "def print_division(dividend:float, divisor:float)->None:\n",
    "    \"\"\"Small, demonstrative division function that prints the quotient\"\"\"\n",
    "    quotient = dividend/divisor\n",
    "    print(f\"My quotient is{quotient}.\")\n",
    "\n",
    "my_dividend = 10\n",
    "my_divisor = 0\n",
    "\n",
    "my_quotient = print_division(my_dividend, my_divisor)\n",
    "\n",
    "print(\"Unfortunately, we will never be able to print this message, because the\"\n",
    "      \"code crashes before due to the uncaught exception.\")\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "3c6bf432",
   "metadata": {},
   "outputs": [],
   "source": [
    "# What if we expected that this error can occurr, and want our program to react\n",
    "# to it in a certain way? Here's how we do it!\n",
    "\n",
    "def print_division(dividend:float, divisor:float)->None:\n",
    "    \"\"\"Small, demonstrative division function that prints the quotient. \n",
    "    If the divisor is 0, we print an appropriate message\"\"\"\n",
    "    try:\n",
    "        quotient = dividend/divisor\n",
    "    except ZeroDivisionError as unfortunate_error:\n",
    "        # In fact, an exception is an object itself. With this syntax, we can\n",
    "        # access the information from our unfortunate_error or do something with\n",
    "        # it, like print its message.\n",
    "        print(f\"Error encountered: {unfortunate_error}\")\n",
    "\n",
    "    # An exception can contain an else statement, that is only executed if no \n",
    "    # error occurs.\n",
    "    else:\n",
    "        print(f\"My quotient is{quotient}.\")\n",
    "\n",
    "    # In some special cases, it may also be required to execute some code after \n",
    "    # a try-except block regardless of whether an exception was raised or not.\n",
    "    # For this, we can add finally. But here, we don't really need it.\n",
    "    finally:\n",
    "        pass\n",
    "\n",
    "my_dividend = 10\n",
    "my_divisor = 0\n",
    "\n",
    "my_quotient = print_division(my_dividend, my_divisor)\n",
    "\n",
    "print(\"But this code is still executed. Our program hasen't crashed, because\"\n",
    "      \"we handle the exception!\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "bab5f8b2",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Sometimes, it is also helpful to raise our own exception. Consider this new\n",
    "# division function, that is supposed to only divide positive numbers. In case\n",
    "# we do receive a negative number in the argument, we want to raise an \n",
    "# exception, because this is not expected:\n",
    "\n",
    "def positive_division(dividend:float, divisor:float) -> None:\n",
    "    \"\"\"Small, demonstrative division function that prints the quotient. \n",
    "    If a negative number is encountered as dividend or divisor, a ValueError is \n",
    "    raised.\"\"\"\n",
    "    if dividend < 0 or divisor <= 0:\n",
    "        # Here, in this case, we raise a value error and give it a helpful \n",
    "        # message.\n",
    "        raise ValueError(\"Negative number encountered during division\")\n",
    "    \n",
    "    quotient = dividend/divisor\n",
    "    print(f\"My quotient is{quotient}.\")\n",
    "\n",
    "try:\n",
    "    positive_division(-1., -1.)\n",
    "except ValueError as my_error:\n",
    "    print(f\"We encountered a ValueError with this message: {my_error}\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "26798c04",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Python has a lot of built in exceptions to choose from. A quick internet\n",
    "# search usually yields the correct one to raise for a given situation. But\n",
    "# sometimes, no inbuilt exception really fits, or we want the exception to be\n",
    "# able to do something specific like storing some extra data.\n",
    "\n",
    "# Let's look at how that would work in our example, for which we'll define our\n",
    "# custom exception DivisionError. We've briefly seen that exceptions are objects\n",
    "# themselves, so it shouldn't surprise that defining a new exception is similar\n",
    "# to defining a class. Thereby it inherits from the Exception base class\n",
    "\n",
    "class DivisionError(Exception):\n",
    "    \"\"\"A custom exception for our positive_division function example. It saves\n",
    "    some additional information about the parameters are included.\n",
    "    \"\"\"\n",
    "    def __init__(self, error_message: str, is_dividend_negative: bool, is_divisor_negative: bool, is_divisor_zero: bool) -> None:\n",
    "        \"\"\"Constructor for our custom exception. Besides the error message, it\n",
    "        takes additional information on the nature of the error.\n",
    "\n",
    "        Parameters\n",
    "        ----------\n",
    "        error_message : str:\n",
    "            Exception error message.\n",
    "        is_dividend_negative : bool\n",
    "            Whether the dividend was 0 during raising of exception.\n",
    "        is_divisor_negative : bool\n",
    "            Whether the divisor was negative during raising of exception.\n",
    "        is_divisor_zero : bool\n",
    "            Whether the divisor was zero during raising of exception.\n",
    "        \"\"\"\n",
    "        self.is_dividend_negative = is_dividend_negative\n",
    "        self.is_divisor_negative = is_divisor_negative\n",
    "        self.is_divisor_zero = is_divisor_zero\n",
    "        super().__init__(error_message)\n",
    "\n",
    "\n",
    "# Let's try our own exception in our positive_division example function\n",
    "def positive_division(dividend:float, divisor:float) -> None:\n",
    "    \"\"\"Small, demonstrative division function that prints the quotient. \n",
    "    If a negative number is encountered as dividend or divisor, a DivisionError \n",
    "    is raised.\"\"\"\n",
    "    # Check the arguments\n",
    "    dividend_negative = dividend < 0\n",
    "    divisor_negative = divisor < 0\n",
    "    divisor_zero = divisor == 0\n",
    "    # If any condition is true, raise the Division error along with arguments\n",
    "    if dividend_negative or divisor_negative or divisor_zero:\n",
    "        raise DivisionError(\"Negative number encountered during division\", \n",
    "                            dividend_negative,\n",
    "                            divisor_negative,\n",
    "                            divisor_zero)\n",
    "    \n",
    "    quotient = dividend/divisor\n",
    "    print(f\"My quotient is{quotient}.\")\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "b65e63ff",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Let's try that function again and see what our custom exception can do:\n",
    "try:\n",
    "    positive_division(-1., -1.)\n",
    "except DivisionError as my_error:\n",
    "    # The error behaves just like any other exception\n",
    "    print(f\"We encountered a DivisionError with this message: {my_error}\")\n",
    "\n",
    "    # But we can now also retrieve some of our custom attributes\n",
    "    print(f\"During raising of exception, dividend was negative: {my_error.is_dividend_negative}\")\n",
    "    print(f\"During raising of exception, divisor was negative: {my_error.is_divisor_negative}\")\n",
    "    print(f\"During raising of exception, divisor was zero: {my_error.is_divisor_zero}\")\n",
    "\n",
    "# Note: Arguably, it's a bit of an overkill to define a custom exception for such\n",
    "# a simple piece of code. It comes with some experience to decide when a custom\n",
    "# exception makes sense."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "a7bdd856",
   "metadata": {},
   "outputs": [],
   "source": [
    "# With great power comes great responsibility\n",
    "\n",
    "# DONT EVER DO THIS\n",
    "try: \n",
    "    print(positive_division(-1., -1.))\n",
    "\n",
    "    # Except all exceptions\n",
    "except Exception:\n",
    "    # And then do nothing to handle it\n",
    "    pass\n",
    "\n",
    "# This is how you end up with broken code that is very tricky to fix. Remember:\n",
    "# Exceptions and their messages are there to help you, not to bother you.\n",
    "# If you just except them all, then you will no longer now whats going on and \n",
    "# where the issue is if something goes wrong\n",
    "\n",
    "# Notice how running this cell produces no output, and it may be tricky to get\n",
    "# behind the reason in a bigger project.\n"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.11.7"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
